name: 'Build and push Spin app'
description: 'Build and push your Spin app to OCI Registry'
author: 'spinframework maintainers'
inputs:
  manifest_file:
    required: false
    description: 'path to spin.toml file'
    default: 'spin.toml'
  registry_reference:
    required: true
    description: 'OCI Registry reference, e.g. ghcr.io/spinframework/cloud-start:v0.0.1. Learn more at https://spinframework.dev/v3/distributing-apps'
  registry:
    required: false
    description: 'Server address of OCI registry'
  registry_username:
    required: false
    description: 'OCI Registry Username'
  registry_password:
    required: false
    description: 'OCI Registry password or personal access token'
outputs:
  digest:
    description: 'The image digest of the pushed app e.g. sha256:...'
runs:
  using: 'node20'
  main: '../../dist/spin/push/index.js'
